using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading.Tasks;

namespace HospitalManagementSystem.Classes
{
    public class Patient
    {
        public static int nextId;
        public string fullName;
        public string address;
        private string email;
        private int phone;

        public Patient(int patientNextId, string patientFullName, string patientAddress, string patientEmail, int patientPhone)
        {
            nextId = patientNextId;
            FullName = patientFullName;
            address = patientAddress;
            email = patientEmail;
            phone = patientPhone;
          
        }


        // *** ID should be generated by the system on object creation, not chosen/inputted by the user. ***
        public int Id
        {
            get { return nextId; }

            set
            {
                //Validation: Ensure that the ID is positive(>=0).
                if (value <= 0)
                {
                    throw new ArgumentException("ID must be a positive(>=0) integer");
                }
                nextId = value;
            }

        }


        public string FullName
        {
            get { return fullName; }

            set
            {
                // Validation: Ensure that the first name is not null or empty.
                if (string.IsNullOrEmpty(value))
                {
                    throw new ArgumentException("Full name cannot be empty.");
                }

                fullName = value;
            }
        }

        
        public string Email
        {
            get { return email; }
            set { email = value; }
        }

        public int Phone
        {
            get { return phone; }
            set { phone = value; }
        }

       

        public override string ToString()
        {
            //customizing the format of the patient's details.

            return $"Patient ID: {nextId}\n" +
                $"Name: {fullName}\n" +
                $"Email: {email}\n" +
                $"Phone: {phone}\n" +
                $"Address: {address}";


        }
    }
}
